name: Build Aries-Backend Master Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@master
      with:
        name: jar-file
        path: aries-backend.jar
    
    - name: Setup QEMU for Multi-Arch
      uses: docker/setup-qemu-action@v2
    
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub to push image
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB.PASSWORD }}
        
    - name: Set current date for image building
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
    
    - name: Build Docker Image and push 
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: niklashaiden/aries-backend:master-${{ env.DATE }}
      
