# This workflow builds a dev image and pushes it to Docker Hub.

name: Build Dev App with Gradle and create a container image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build-dev-jar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle for building
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1

    - name: Build Aries Spring Boot Jar
      run: |
        chmod +x ./gradlew
        ./gradlew bootJar
    
    - name: Move the Jar File
      run: mv build/libs/$(ls build/libs) aries-backend-dev.jar
    
    - uses: actions/upload-artifact@master
      with: 
        name: Aries Backend Jar
        path: aries-backend-dev.jar
     
  build-dev-docker-image:
    runs-on: ubuntu-latest
    needs: build-jar
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@master
      with:
        name: Aries Backend Jar
        path: aries-backend-dev.jar
    
    - name: Setup QEMU for Multi-Arch
      uses: docker/setup-qemu-action@v2
    
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub to push image
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build Docker Image and push 
      uses: docker/build-push-action@v3
      with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: niklashaiden/aries-backend:latest-dev
